#pragma once

#include <cstdint>

namespace plume
{
    struct RenderDevice;
}

namespace DLSSNR
{
    // DLSS Neural Rendering is evaluated from the native DLSS output. RenoDX's
    // reference path identifies that source as linear BT.709 before preparing
    // the image for the NR model, so keep the source convention explicit here
    // instead of inheriting the swapchain encoding.
    enum class SourceEncoding : uint32_t
    {
        LinearBT709,
    };

    // The prerelease DLSSNR.Style field is exposed as Model A/B/C by RenoDX.
    // The labels are ordered exactly as the style values consumed by the
    // supplied runtime; Model B is therefore style 1.
    enum class Model : uint32_t
    {
        A = 0,
        B = 1,
        C = 2,
    };

    struct Settings
    {
        SourceEncoding sourceEncoding = SourceEncoding::LinearBT709;
        Model model = Model::B;
        float intensity = 1.0f;
        float localToneStrength = 0.31f;
        float globalToneStrength = 1.0f;
        float localStructureStrength = 1.0f;
    };

    // Fixed project profile requested for the initial DLSS 5 NR integration.
    const Settings& GetSettings();

    // Reads the persistent Video option generated by the DLSS-NR CMake layer.
    bool IsEnabled();

    // Loads and validates nvngx_dlssnr.dll on the selected D3D12 adapter. The
    // Feature-18 create/evaluate bridge is intentionally a separate stage so
    // selecting On never reports NR as active before NGX evaluation is wired.
    bool SetDevice(plume::RenderDevice* device);
    void Shutdown();

    bool IsRuntimeReady();
    const char* GetStatus();
}
